apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: roboshop
data:
  MYSQL_DATABASE: "cities"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: roboshop
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: Um9ib1Nob3BAMQ==
  MYSQL_USER: c2hpcHBpbmc=
  MYSQL_PASSWORD: Um9ib1Nob3BAMQ==
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: roboshop
  labels:
    app: mysql
    project: roboshop
    tier: db
spec:
  selector:
    matchLabels:
      app: mysql
      project: roboshop
      tier: db
  serviceName: "mysql"
  replicas: 2
  template:
    metadata:
      labels:
        app: mysql
        project: roboshop
        tier: db
    spec:
      containers:
      - name: mysql
        image: joindevops/mysql:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: mysql
        - secretRef:
            name: mysql
        volumeMounts:
        - name: mysql
          mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mysql
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "ebs-sc"
        resources:
          requests:   
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
  labels:
    app: mysql
    project: roboshop
    tier: db
spec:
  selector:
    app: mysql
    project: roboshop
    tier: db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  clusterIP: None
