apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: roboshop
  labels: # these labels are deployment labels
    app: redis
    project: roboshop
    tier: db
spec:
  selector:
    matchLabels: # these labels are used to find the pods
      app: redis
      project: roboshop
      tier: db
  serviceName: "redis"
  replicas: 2
  template:
    metadata:
      labels: # these labels are pod labels
        app: redis
        project: roboshop
        tier: db
    spec:
      containers:
      - name: redis
        image: redis
        imagePullPolicy: Always
        volumeMounts:
        - name: redis
        mountPath: /data
    volumeClaimTemplates:
      - metadata:
          name: redis
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: "ebs-sc"
          resources:
            requests:   
              storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
spec:
  selector:
    app: redis
    project: roboshop
    tier: db
  ports:
  - protocol: TCP
    port: 6379 #service-port
    targetPort: 6379 #container-port