apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  labels: # these labels are deployment labels
    app: payment
    project: roboshop
    tier: app
spec:
  replicas: 2
  selector:
    matchLabels: # these labels are used to find the pods
      app: payment
      project: roboshop
      tier: app
  template:
    metadata:
      labels: # these labels are pod labels
        app: payment
        project: roboshop
        tier: app
    spec:
      containers:
      - name: payment
        image: anilnadikuda/payment:v1
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory:  "256Mi"
        envFrom:
        - secretRef:
            name: payment
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: payment
  namespace: roboshop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: v1
kind: Secret
metadata:
  name: payment
  namespace: roboshop
type: Opaque
data:
  AMQP_USER: cm9ib3Nob3A=
  AMQP_PASS: cm9ib3Nob3AxMjM=
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: roboshop
spec:
  selector:
    app: payment
    project: roboshop
    tier: app
  ports:
  - protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 #container-port