apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  namespace: roboshop
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: cm9ib3Nob3A=
  RABBITMQ_DEFAULT_PASS: cm9ib3Nob3AxMjM=
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: roboshop
  labels: # these labels are deployment labels
    app: rabbitmq
    project: roboshop
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels: # these labels are used to find the pods
      app: rabbitmq
      project: roboshop
      tier: db
  template:
    metadata:
      labels:
        app: rabbitmq
        project: roboshop
        tier: db
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq
        volumeMounts:
        - name: rabbitmq
          mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: rabbitmq
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "ebs-sc"
        resources:
          requests:   
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
spec:
  selector:
    app: rabbitmq
    project: roboshop
    tier: db
  ports:
  - protocol: TCP
    port: 5672 #service-port
    targetPort: 5672 #container-port