apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    app: mongodb
    project: roboshop
    tier: db
spec:
  selector:
    matchLabels:
      app: mongodb
      project: roboshop
      tier: db
  serviceName: "mongodb"
  replicas: 2
  template:
    metadata:
      labels:
        app: mongodb
        project: roboshop
        tier: db
    spec:
      containers:
      - name: mongodb
        image: joindevops/mongodb:v1
        volumeMounts:
        - name: mongodb
          mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongodb
      spec:
        accessModes: [ "ReadWriteOnce" ]
        StorageClassName: "ebs-sc"
        resources:
          requests:   
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    app: mongodb
    project: roboshop
    tier: db
spec:
  selector:
    app: mongodb
    project: roboshop
    tier: db
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  clusterIP: None
